
export const colors = {
  light: {
    background: '#F9F9F9',
    text: '#1A1A1A',
    primaryText: '#000',
    secondaryText: '#666',
    card: '#FFFFFF',
    border: '#EFEFEF',
    pillText: '#555',
    pillBorder: '#DDD',
    pillBackground: 'transparent',
    inputBackground: '#EFEFEF',
    inputBorder: '#DDD',
    error: '#D32F2F',
    headerBackground: 'rgba(240, 240, 240, 0.8)',
    headerTitle: '#000',
    backButton: 'rgba(0,0,0,0.1)',
    backButtonText: '#000',
    accent: '#000000',
  },
  dark: {
    background: '#000000',
    text: '#E5E5E5',
    primaryText: '#FFF',
    secondaryText: '#999',
    card: '#1A1A1A',
    border: '#2A2A2A',
    pillText: '#CCC',
    pillBorder: '#444',
    pillBackground: '#222',
    inputBackground: '#222',
    inputBorder: '#333',
    error: '#FF6B6B',
    headerBackground: 'rgba(30, 30, 30, 0.8)',
    headerTitle: '#FFF',
    backButton: 'rgba(0,0,0,0.3)',
    backButtonText: '#FFF',
    accent: '#FFFFFF',
  },
};
