/**
 * Environment Configuration
 * 
 * IMPORTANT: This file is auto-generated from .env.txt
 * To update API keys:
 * 1. Edit .env.txt in the root directory
 * 2. Run: node scripts/sync-env.js
 * 
 * DO NOT edit this file directly - your changes will be overwritten!
 */

const ENV_CONFIG = {
  LASTFM_API_KEY: '4a9f5581a9cdf20a699f540aa52a95c9',
  SPOTIFY_CLIENT_ID: '3b04b56282cf497fbc68c6bf8cb51438',
  SPOTIFY_CLIENT_SECRET: 'b89842acfa4d4ec4ad55bdac57a1e4a2',
  PAXSENIX_API_KEY: 'sk-paxsenix-BsjVL0-o7w0TEZhzSxcFCkispUuWMQ_cGfRWa6JMxGlOJxox',
  APPLE_MUSIC_DEVELOPER_TOKEN: 'eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IlZGTUo5QTVQVDQifQ.eyJpYXQiOjE3NjQ0NjQ4MTcsImV4cCI6MTc4MDAxNjgxNywiaXNzIjoiNEI0NDZUQUZMViJ9.COJFDu8eRZtJ123Y1vE70jaerHiMc-XOmlh6yshnFV6jrGR-cKETqSj7zcBu_MZ9fFOHgj0AaEyt4eEpso9JPQ',
};

// Validation: Check for missing keys
export function validateConfig() {
  const missing = [];
  Object.entries(ENV_CONFIG).forEach(([key, value]) => {
    if (!value || value === 'YOUR_KEY_HERE') {
      missing.push(key);
    }
  });
  
  if (missing.length > 0) {
    console.warn(`[ENV CONFIG] Missing or placeholder API keys: ${missing.join(', ')}`);
    console.warn('[ENV CONFIG] Please update .env.txt and run: node scripts/sync-env.js');
  }
  
  return missing.length === 0;
}

// Export individual keys for easy access
export const {
  LASTFM_API_KEY,
  SPOTIFY_CLIENT_ID,
  SPOTIFY_CLIENT_SECRET,
  PAXSENIX_API_KEY,
  APPLE_MUSIC_DEVELOPER_TOKEN,
} = ENV_CONFIG;

export default ENV_CONFIG;
