const fs = require('fs');
const path = require('path');

/**
 * Sync Script for Environment Configuration
 * 
 * This script reads .env and generates src/config/envConfig.js
 * Usage: node scripts/sync-env.js
 */

const ENV_FILE = path.join(__dirname, '..', '.env');
const CONFIG_FILE = path.join(__dirname, '..', 'src', 'config', 'envConfig.js');

function parseEnvFile(content) {
  const config = {};
  const lines = content.split('\n');
  
  for (const line of lines) {
    const trimmed = line.trim();
    
    // Skip comments and empty lines
    if (!trimmed || trimmed.startsWith('#')) {
      continue;
    }
    
    // Parse KEY=VALUE
    const match = trimmed.match(/^([A-Z_]+)=(.*)$/);
    if (match) {
      const [, key, value] = match;
      config[key] = value;
    }
  }
  
  return config;
}

function generateConfigFile(config) {
  const entries = Object.entries(config)
    .map(([key, value]) => `  ${key}: '${value}',`)
    .join('\n');
  
  return `/**
 * Environment Configuration
 * 
 * IMPORTANT: This file is auto-generated from .env.txt
 * To update API keys:
 * 1. Edit .env.txt in the root directory
 * 2. Run: node scripts/sync-env.js
 * 
 * DO NOT edit this file directly - your changes will be overwritten!
 */

const ENV_CONFIG = {
${entries}
};

// Validation: Check for missing keys
export function validateConfig() {
  const missing = [];
  Object.entries(ENV_CONFIG).forEach(([key, value]) => {
    if (!value || value === 'YOUR_KEY_HERE') {
      missing.push(key);
    }
  });
  
  if (missing.length > 0) {
    console.warn(\`[ENV CONFIG] Missing or placeholder API keys: \${missing.join(', ')}\`);
    console.warn('[ENV CONFIG] Please update .env.txt and run: node scripts/sync-env.js');
  }
  
  return missing.length === 0;
}

// Export individual keys for easy access
export const {
  LASTFM_API_KEY,
  SPOTIFY_CLIENT_ID,
  SPOTIFY_CLIENT_SECRET,
  PAXSENIX_API_KEY,
  APPLE_MUSIC_DEVELOPER_TOKEN,
} = ENV_CONFIG;

export default ENV_CONFIG;
`;
}

function main() {
  console.log('🔄 Syncing environment configuration...');
  
  // Check if .env exists
  if (!fs.existsSync(ENV_FILE)) {
    console.error('❌ Error: .env not found!');
    console.error('   Please create .env in the root directory.');
    process.exit(1);
  }
  
  // Read and parse .env.txt
  const envContent = fs.readFileSync(ENV_FILE, 'utf8');
  const config = parseEnvFile(envContent);
  
  if (Object.keys(config).length === 0) {
    console.error('❌ Error: No configuration found in .env');
    process.exit(1);
  }
  
  console.log(`📋 Found ${Object.keys(config).length} configuration keys`);
  
  // Generate config file
  const configContent = generateConfigFile(config);
  
  // Ensure directory exists
  const configDir = path.dirname(CONFIG_FILE);
  if (!fs.existsSync(configDir)) {
    fs.mkdirSync(configDir, { recursive: true });
  }
  
  // Write config file
  fs.writeFileSync(CONFIG_FILE, configContent, 'utf8');
  
  console.log('✅ Successfully generated src/config/envConfig.js');
  console.log('');
  console.log('📝 Configuration keys:');
  Object.keys(config).forEach(key => {
    console.log(`   - ${key}`);
  });
  console.log('');
  console.log('⚠️  Remember: Never commit .env to version control!');
}

main();
